# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Building.create(:name => '京都大学工学部7号館', :floor_size => 4, :latitude => 35.027452, :longitude => 135.783750)
Building.create(:name => '京都大学工学部8号館', :floor_size => 4, :latitude => 35.026662, :longitude => 135.781842)

Toilet.create(:building_id => 1, :store_name => 'エレベータ横', :latitude => 35.027531, :longitude => 135.783817, :floor => 1, :sex => 0)
Toilet.create(:building_id => 1, :store_name => '階段横', :latitude => 35.027531, :longitude => 135.783817, :floor => 1, :sex => 1)
Toilet.create(:building_id => 1, :store_name => '階段上がってすぐ', :latitude => 35.027531, :longitude => 135.783817, :floor => 2, :sex => 1)
Toilet.create(:building_id => 2, :store_name => '', :latitude => 35.026675, :longitude => 135.781893, :floor => 1, :sex => 0)
Toilet.create(:building_id => 2, :store_name => '', :latitude => 35.026675, :longitude => 135.781893, :floor => 2, :sex => 1)

Room.create(:toilet_id => 1, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 1, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 1, :available => true, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 1, :available => true, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 1, :available => true, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 1, :available => true, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 2, :available => true, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 2, :available => true, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 2, :available => false, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 2, :available => false, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 2, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 2, :available => true, :washlet => true, :multipurpose => true)
Room.create(:toilet_id => 3, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 3, :available => false, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 3, :available => false, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 3, :available => false, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 3, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 3, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 4, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 4, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 4, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 4, :available => false, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 4, :available => false, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 4, :available => true, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 5, :available => true, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 5, :available => true, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 5, :available => true, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 5, :available => true, :washlet => false, :multipurpose => false)
Room.create(:toilet_id => 5, :available => true, :washlet => true, :multipurpose => false)
Room.create(:toilet_id => 5, :available => true, :washlet => true, :multipurpose => false)
